### ISSUE TITLE
Users being unexpectedly disabled

### ISSUE THREAD

**Issue by russss** [emfcamp/freescout-docker#1]
Ben has seen an issue where he consistently gets into a redirect loop when accessing Freescout with MS Edge. This ends up with the account being locked in Freescout and an admin has to unlock it. I took a look at the logs and there was nothing obvious.

I am hesitant to test this myself in production because if my account gets logged out it's not terribly easy to unlock it. I haven't had time to try and reproduce it in dev.

**Comment by jellybob** [comment]
It looks like this may be a bug (feature?) in Edge: https://learn.microsoft.com/en-us/entra/identity-platform/msal-js-known-issues-ie-edge-browsers

TL;DR: If the auth process crosses between two different Edge security zones session storage will be flushed by the browser, resulting in any credentials not being persisted. Microsoft's Azure auth thing is being impacted by this, so hopefully they can throw things at the Edge team until it gets fixed.

If they can't/don't fix it, it may be necessary to poke at Vouch and persuade it to store credentials some other way, but I'm hesitant to do so for now.

**Comment by marksteward** [comment]
The linked article seems unlikely to be the cause, unless Ben's added one of our domains to Trusted Sites (in which case, don't do that).

**Comment by Jonty** [comment]
It might be useful to get packet dumps from both chrome and edge against the same setup so we can compare them - I don't have a windows install to do this unfortunately.

**Comment by russss** [comment]
I *may* have got the wrong causation here. I think it's possible that the freescout account is getting disabled for some other reason and that's causing the redirect loop. But I have no idea why.

**Comment by marksteward** [comment]
The original description was:

> I'm now getting ERR_TOO_MANY_REDIRECTS on Freescout. Worked for the first few page loads.

So that would track with something else causing it. I've done a lot of clicking around in Edge and can't reproduce it.

**Comment by russss** [comment]
OK, so actually two users are being disabled by Freescout's "Sync Mailbox Permission" task, for some reason.

This is confusing because disabling a user isn't a mailbox-level permission, and also there's nothing obviously different about these two users.

**Comment by russss** [comment]
This was because the freescout LDAP plugin couldn't fetch all the users because uffd-ldapd uses integers as pagination cookies and `'0' == false` in PHP. Naturally.
